# Site settings
title: "#./wouter.sh"
description: "Cloud Engineer, father of Sid and Fay, partner of Donna"
baseurl: "" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "" # default is empty
author: "Wouter in 't Veld"
site.title.custom: "./wouter.sh"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics: UA-105175553-1
disqus_shortname:
