baseurl      = "/"
languageCode = "en-us"
theme        = "hello-friend-ng"
googleAnalytics = "UA-139515521-1"

[blackfriday]
    hrefTargetBlank = true
[params]
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04 -0700"

    # Metadata mostly used in document's head
    description     = "Homepage and blog by Wouter in 't Veld"
    keywords        = "homepage, blog, cloud, development, programming"
    images          = [""]


    # Directory name of your blog content (default is `content/posts`)
    contentTypeName = "posts"
    # Default theme "light" or "dark"
    defaultTheme = "dark"

    # Social icons
    [[params.social]]
        name = "twitter"
        url  = "https://twitter.com/wouterintveld"

    [[params.social]]
        name = "email"
        url  = "mailto:hashbang@wouter.sh"

    [[params.social]]
        name = "github"
        url  = "https://github.com/wouter-intveld"

    [[params.social]]
        name = "linkedin"
        url  = "https://www.linkedin.com/in/wouterintveld"

    # [[params.social]]
    #     name = "instagram"
    #     url  = "https://www.instagram.com/def4ce/"

    # [[params.social]]
    #     name = "steam"
    #     url  = "https://steamcommunity.com/id/deface/"

    [languages]
    [languages.en]
        title          = "Wouter in 't Veld"
        homeSubtitle   = "Cloud Engineer"
        subtitle       = "Cloud Engineer @ Coolblue. Father of Sid and Fay. Partner of Donna."
        keywords       = ""
        copyright      = "Wouter in 't Veld"
        readOtherPosts = "Read other posts"

        [languages.en.params.logo]
        logoText     = "#./wouter.sh"
        logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    # [languages.en.menu]
    #   [[languages.en.menu.main]]
    #     identifier = "about"
    #     name = "About"
    #     url = "/about"
    #   [[languages.en.menu.main]]
    #     identifier = "showcase"
    #     name = "Showcase"
    #     url = "/showcase"

# And you can even create generic menu
[menu]
[[menu.main]]
    identifier = "cv"
    name       = "Resume"
    url        = "/cv"
    weight     = "2"    
[[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
    weight     = "3"    
[[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
    weight     = "1"